# Generated by Django 4.2.4 on 2023-08-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0002_remove_producto_descripcion_remove_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
